### ISSUE TITLE
Improve conda dependency generation from pyproject.toml?

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/copier_template#189]
A `pyproject.toml` like this:
```toml
dependencies = [
  "abcde >= 24.06.0",
]
```
currently leads to a failing `conda-build`. Apparently `conda` does not like the spaces around `>=`.

Can/should https://github.com/scipp/cyclebane/blob/3b67e2d2c0fb8b03d3ce0f4306b86d33fde20efd/conda/meta.yaml#L10-L11 be adapted to remove spaces? Or should we just "remember" to not use spaces in `pyproject.toml`?

**Comment by jokasimr** [comment]
Is this fixed with https://github.com/scipp/essreduce/pull/40 merged? What's left to do? Should this be closed?

**Comment by SimonHeybrock** [comment]
Not fixed (in the template). What is left to do is think about the last paragraph in the issue description. Note that I have so far seen 2 project where we have had this problem.

**Comment by jl-wynen** [comment]
Neither package names nor version numbers are allowed to contain spaces. So it is safe, as far as I can tell, to remove all spaces.

It should be possible to replace spaces by using [replace](https://jinja.palletsprojects.com/en/3.0.x/templates/#jinja-filters.replace) in https://github.com/scipp/cyclebane/blob/3b67e2d2c0fb8b03d3ce0f4306b86d33fde20efd/conda/meta.yaml#L22.
